name: BilicraftDanmaku
version: ${project.version}
main: com.bilicraft.bilicraftdanmaku.BilicraftDanmaku
api-version: 1.17
authors: [ ntrwansui ]
description: Plugin-side support for BilicraftComments Mod
permissions:
  bilicraftdanmaku.*:
    description: Gives access to all bilicraftdanmaku actions
    default: op
    children:
      bilicraftdanmaku.send: true
  bilicraftdanmaku.send:
    description: Allowed All mode
    default: op
    children:
      bilicraftdanmaku.send.normal: true
      bilicraftdanmaku.send.top: true
      bilicraftdanmaku.send.bottom: true
      bilicraftdanmaku.send.reverse: false
  bilicraftdanmaku.send.normal:
    description: Allowed normal mode
    default: true
  bilicraftdanmaku.send.top:
    description: Allowed top mode
    default: op
  bilicraftdanmaku.send.bottom:
    description: Allowed buttom mode
    default: op
  bilicraftdanmaku.send.reverse:
    description: Allowed reverse mode
    default: false