name: BilicraftDanmaku
version: ${project.version}
main: com.bilicraft.bilicraftdanmaku.BilicraftDanmaku
api-version: 1.17
authors: [ ntrwansui ]
description: Plugin-side support for BilicraftComments Mod
permissions:
  bilicraftdanmaku.*:
    description: Gives access to all bilicraftdanmaku actions
    default: op
    children:
      bilicraftdanmaku.denied: false
      bilicraftdanmaku.mode: true
  bilicraftdanmaku.mode:
    description: Allowed All mode
    default: op
    children:
      bilicraftdanmaku.normal: true
      bilicraftdanmaku.top: true
      bilicraftdanmaku.buttom: true
      bilicraftdanmaku.reverse: false
  bilicraftdanmaku.normal:
    description: Allowed normal mode
    default: true
  bilicraftdanmaku.top:
    description: Allowed top mode
    default: op
  bilicraftdanmaku.buttom:
    description: Allowed buttom mode
    default: op
  bilicraftdanmaku.reverse:
    description: Allowed reverse mode
    default: false
  bilicraftdanmaku.denied:
    description: Denied this user's danmaku
    default: not op